// Generated by https://quicktype.io

export interface CategoriesResponseAPI {
  message:  string;
  response: Category[];
}

export interface CategoryResponseAPI {
  message:  string;
  response: Category;
}

export interface Category {
  id:          number;
  name:        string;
  description: string;
  created_at:  string;
  updated_at:  string;
}
