// Generated by https://quicktype.io

export interface TagsResponseAPI {
  message:  string;
  response: Tag[];
}

export interface TagResponseAPI {
  message:  string;
  response: Tag;
}

export interface Tag {
  id:          number;
  name:        string;
  description: string;
  created_at:  string;
  updated_at:  string;
}
