// Generated by https://quicktype.io

export interface UsersResponseAPI {
  message:  string;
  response: User[];
}

export interface UserResponseAPI {
  message:  string;
  response: User;
}

export interface LoginResponseAPI {
  message:  string;
  response: Token;
}

export interface Token {
  token: string
}

export interface User {
  id:          number;
  username:    string;
  email:       string;
  roleEntity:  Role;
  created_at:  string;
  updated_at:  string;
}

export interface Role {
  id:          number;
  name:        string;
  description: string;
}
